### ISSUE TITLE
is this your re-implement or from the author of the paper?

### ISSUE THREAD

**Issue by autosquid** [avanindra/EPVH#1]
Just a simple question: is this your re-implement or from the author of the paper? The author used to provide his code, but not any more.

And is the code functional now?

**Comment by avanindra** [comment]
Hi,

Yes , the code is my re-implementation of EPVH from the paper. It was a
part of my another project , I pulled it out and pushed it to github. It
needs some editing to become functional and get compiled . The Camera
parameters class  need fixing , otherwise the code would work. When I get
some time , I would fix it. It needs day or two work.

**Comment by autosquid** [comment]
@avanindra  I have looking for the epvh implementation for days. And yours is the only hope. Really hope you can make it work soon.   And  I noticed a few commits hours ago. Thanks for your work.

P.S. I am reading your code now.  :+1:

**Comment by autosquid** [comment]
> Yes , the code is my re-implementation of EPVH from the paper. It was a
> part of my another project , I pulled it out and pushed it to github. It

So does that mean the correctness of the part of code has been verified?

**Comment by avanindra** [comment]
Yes , the code works except few weird cases which can be handled later. The code is verified. I would update the working demo. It lacks documentation and need to remove some unused code. I am updating it , may be soon it would become functional.
