### ISSUE TITLE
how about a naive half space intersection implementation.

### ISSUE THREAD

**Issue by autosquid** [avanindra/EPVH#6]
This is a more or less general question, which baffled me a lot.

Why there is no naive implementation with half space intersection?

One flaw I can see (but now sure) is that half space has difficulties with silhouettes with holes. Do you known any other reasons?

**Comment by avanindra** [comment]
I avoided explicit intersections with plane , because technically it was not necessary. Up to computation of viewing edges , all the intersections are computed in image space. Maximal point computation requires 3d intersection with generators , but if you notice clipping would always be performed at the common line between two half spaces of generators , so all we are looking at , is intersection between two 3d lines. In any case , we can use half space intersection in computeMaximalPoint method , if it improves the quality.

**Comment by autosquid** [comment]
thx, I am closing it!
